name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Asseble
        run: ./gradlew app:assemble
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Lint
        run: ./gradlew app:lint
      - uses: actions/upload-artifact@master
        with:
          name: Lint Results
          path: app/build/reports/lint-results.html
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test
        run: ./gradlew app:test
      - uses: actions/upload-artifact@master
        with:
          name: Test Results
          path: app/build/reports/tests
