name: Android New Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setting GITHUB_RELEASE_ID
        run: echo $GITHUB_REF | cut -c 10-
